### ISSUE TITLE
Place asset crashing

### ISSUE THREAD

**Issue by Lightset1978** [zyme-xd/rblx-rip#3]
The place asset doesn't work.
It does download a .rbxl file but it's only 1kb big.
And when I open it on roblox studio it gives me an error.
Or sometimes it just plan up crashes.
I tried 7 times with different game links and all failed.

**Comment by ghost** [comment]
it seems that the place you're trying to download has to be uncopylocked, according to the creator
damn i was also hoping i could rip any game but whatever i guess

**Comment by harborseals** [comment]
uncopylocked places do not work
